### ISSUE TITLE
Example config for Source Initiated forwarding?

### ISSUE THREAD

**Issue by ghost** [PowerShell/xWindowsEventForwarding#12]
Can I get an example of how source initiated forwarding would be configured via DSC?

I set up a basic configuration but it fails with error "threw one or more non-terminating errors while running the Set-TargetResource functionality."

configuration SetupCollector
{
    Import-DscResource -ModuleName xWindowsEventForwarding
    xWEFCollector Enabled
    {
        Ensure = "Present"
        Name = "Enabled"
    }
    xWEFSubscription SecurityEvents
    {
       SubscriptionID = "Security events"
       SubscriptionType = "SourceInitiated"
       DependsOn = "[xWEFCollector]Enabled"
       LogFile = "ForwardedEvents"
       Query = @('Security:*')
       AllowedSourceDomainComputers = 'O:NSG:NSD:(A;;GA;;;DC)(A;;GA;;;NS)'
    } 
}

SetupCollector

From what I saw in the MSFT_xWEFSubscription.psm1, the permission for AllowedSourceDomainComputers is set by default. But omitting the value also causes the configuration to fail.

**Comment by johlju** [comment]
Could you please provide the verbose output and the error message that is thrown?
Is this the same issue as #9?
